# Generated by Django 3.1.3 on 2021-01-02 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('api', '0002_rating_ratingstar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratingstar',
            options={'ordering': ['-value'], 'verbose_name': 'Звезда рейтинг', 'verbose_name_plural': 'Звёзды рейтинга'},
        ),
        migrations.AlterField(
            model_name='rating',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Категория'),
        ),
    ]
